import { type TeamType } from '../../src/types/team.types'

export const team: TeamType = [
  {
    firstName: 'Kevin',
    lastName: 'Bal',
    description: `<p>Kevin, een geconventioneerde therapeut en mede-eigenaar van de praktijk, studeerde in 2004 af als licentiaat in de kinesitherapie. Van onze 5 collega's is hij reeds het langst aan het werk in onze reeds 30 jaren bestaande praktijk.</p><p>Naast zijn activiteiten in de praktijk is hij ook werkzaam op de revalidatieafdeling APRA van het AZ Monica Antwerpen. Hij houdt zich op beide sites vooral bezig met orthopedische geneeskunde en manuele therapie.</p><p>Verder specialiseerde hij zich in de behandeling van brandwonden en littekens bij de Scar Academy van het brandwondencentrum Oscare. In een verdere zoektocht naar een optimale behandeling verdiepte hij zich in het Medical Taping Concept, het Mulligan Concept en Dry Needling. De laatste jaren verdiepte hij zich verder in de myofasciale anatomie en de behandelmodaliteiten daarvan. Hiervoor volgde hij de Anatomy Trains opleiding en past hij de Ergon soft Tissue Technique toe. Sinds 2021 is hij lid van het schoudernetwerk Vlaanderen.</p>`,
    role: 'Manuele therapie – kinesitherapie',
    geconventioneerd: true,
    specialitities: [
      'Brandwonden en littekens',
      'Myofasciale therapie',
      'Dry needling',
    ],
    imageFileName: 'kevin-bal.png',
    imageWidth: '534',
    imageHeight: '800',
    backgroundPosition: {
      top: '-15px',
    },
    phone: '0477 92 72 02',
    appointmentUrl: 'http://www.q-top.be/Online-planner/NL/?root=kq35040',
  },
  {
    firstName: 'Sven',
    lastName: 'Meiresone',
    description: `<p>Sven is geconventioneerde therapeut en mede-eigenaar van de praktijk, studeerde in 2009 af aan de UA als Master in de Kinesitherapie en Revalidatiewetenschappen. Na deze opleiding verdiepte hij zich in een Master na Master Manuele Therapie aan de VUB wat maakt dat u voor al uw musculoskeletale klachten bij hem terecht kan.</p>
      <p>Hij beheerst hiernaast ook het medical taping concept, Mulligan-technieken, en Dry Needling. Naast zijn werk in de praktijk is hij ook actief op de dienst ambulante revalidatie van ZNA Middelheim waar u bij hem terecht kan voor onder andere hydrotherapie en revalidatie. Buiten het werk houdt hij zich bezig met parapente, diepzeeduiken, fietsen en lopen. De opgedane ervaringen tijdens marathons & dodentochten, maken van hem eveneens uw ideale loopbegeleider. Ook voor fietsadvies kunt u op hem beroep doen aangezien de verdieping in bike-fitting en lactaattesten werd afgerond. Meer informatie vindt u op zijn website <a href="https://www.kimante.be" title="www.kimante.be">www.kimante.be</a></p>`,
    role: 'Manuele therapie – kinesitherapie',
    geconventioneerd: true,
    specialitities: [
      'Myofasciale therapie',
      'Dry needling',
      'Loopbegeleiding',
      'Bike fitting',
    ],
    imageFileName: 'sven-meiresone.jpg',
    imageWidth: '228',
    imageHeight: '292',
    phone: '0472 28 70 20',
    appointmentUrl: 'http://www.q-top.be/Online-planner/NL/?root=kq37810',
  },
  {
    firstName: 'Aiko',
    lastName: 'Deckers',
    geconventioneerd: false,
    description: `<p>Aiko studeerde in 2016 af aan de VUB als Master in de Kinesitherapie en Revalidatiewetenschappen met specialisatie Manuele Therapie, dit na een Master in Bewegingswetenschappen en Lichamelijke Opvoeding. Nadien volgde hij nog een postgraduaat Manuele Therapie aan de UGent aangevuld met specialisaties in Dry Needling.</p>
      <p>Hij bouwde daarnaast heel wat ervaring op binnen de sportrevalidatie en sportkinesitherapie bij verscheidene voetbal-, hockey-, basketbal-, volleybal-, handbal- en basebalteams wat van hem een geschikte begeleider en motivator maakt. Naast de tewerkstelling in onze praktijk werkt hij ook nog halftijds in WZC Huis Vandecruys. De weinige vrijetijd die Aiko overhoudt spendeert hij aan avontuurlijke reizen, padel, skiën, snowboarden en zijn in 2020 geboren tweeling.</p>`,
    role: 'Manuele therapie – kinesitherapie',
    specialitities: ['Sportkinesitherapie', 'Dry needling'],
    imageFileName: 'aiko-deckers.jpeg',
    imageWidth: '1157',
    imageHeight: '868',
    phone: '0476 36 87 99',
    appointmentUrl:
      'https://www.q-top.be/Online-planner/NL/?root=kq52934&location=kinegroepzuid',
    backgroundPosition: {
      left: '-29px',
      top: '-20px',
    },
    maxWidth: '150%',
  },
  {
    firstName: 'Manon',
    lastName: 'Van kerkhoven',
    geconventioneerd: false,
    description: `<p>Manon is een jonge gedreven kinesiste met reeds 2 jaar ervaring in een zelfstandige praktijk voor kinderen en volwassenen. In 2022 behaalde ze aan de KU Leuven haar masterdiploma revalidatie en bewegingswetenschappen kinesitherapie met een specialisatie in baby- en kinderkinesitherapie. U kan bij haar terecht voor algemene kinesitherapie, manuele therapie, dry-needling, oefentherapie, lymfedrainage, postoperatieve revalidatie, perinatale kinesitherapie. Specifiek voor baby’s en kinderen kan u bij haar terecht voor ademhalingskinesitherapie, ontwikkelingsstimulatie (grove en fijne motoriek), neurologische en orthopedische problemen, plagiocephalie en voorkeurshoudingen.</p>`,
    role: 'Manuele therapie - kinesitherapie',
    specialitities: ['Sportkinesitherapie', 'Dry needling'],
    imageFileName: 'manon_van_kerkhoven.png',
    imageWidth: '355',
    imageHeight: '428',
    phone: '0492657249',
    appointmentUrl:
      'https://agenda.crossuite.com/KGZ/l/n5r4v5z5j454u2944444/o/54335474r2',
    backgroundPosition: {
      left: '-20px',
      top: '-20px',
    },
    maxWidth: '150%',
  },
  {
    firstName: 'Daphne',
    lastName: 'Lai',
    description: `<p>Daphne Lai vult ons team aan als diëtiste en tabakoloog sinds april 2019. U kan bij haar terecht voor voedingsadvies op maat en rookstopbegeleiding. Voor meer info en het maken van een afspraak verwijzen we u graag door naar haar website <a href="https://www.daphnelai.be" title='www.daphnelai.be' target='_blank'>www.daphnelai.be</a>.</p>`,
    role: 'Diëtiste - tabakoloog',
    imageFileName: 'daphne-lai.jpg',
    specialitities: [],
    imageWidth: '754',
    imageHeight: '1016',
    phone: '0485 74 64 20',
    appointmentHtml:
      '<a href="https://www.daphnelai.be/" target="_blank" class="underline" title="http://www.daphnelai.be/">http://www.daphnelai.be/</a>',
  },
  {
    firstName: 'Pieter',
    lastName: 'Vermeiren',
    description: `<p>Pieter Vermeiren vult sinds januari 2024 ons team aan als gediplomeerd en wel onderricht podoloog. Met zijn bagage aan kennis en ervaring kan u bij hem terecht voor al uw klachten die u op podologische wijze wenst te benaderen. Voor meer informatie en het maken van een afspraak verwijzen we u graag door naar zijn website <a href='https://www.stepup-podologie.be' title='stepup-podologie.be'>stepup-podologie.be</a>.</p>`,
    role: 'Podoloog',
    imageFileName: 'pieter-vermeiren.png ',
    specialitities: [],
    imageWidth: '431',
    imageHeight: '452',
    phone: '0492 16 29 28',
    appointmentHtml:
      '<a href="https://www.stepup-podologie.be" target="_blank" class="underline" title="https://www.stepup-podologie.be">https://www.stepup-podologie.be</a>',
  },
  {
    firstName: 'Yanuka',
    lastName: 'Moniaga',
    description: `<p>Yanuka Moniaga vult sinds de zomer van 2024 ons team aan als personal trainer. Met haar jarenlange ervaring als algemeen sportcoach en karate-instructeur én momenteel startende aan haar afstudeerjaar Master in de Kinesitherapie & Revalidatiewetenschappen vormt ze het ideale verlengstuk van ons huidige team. Aanvankelijk zal ze zich bezighouden met 1 op 1 sessies personal training met een optie tot de vorming van small-group-training (2-3 personen). Voor meer informatie en voor het maken van een afspraak verwijzen we u graag door naar haar website <a href="http://www.yanuka.be">www.yanuka.be</a>.</p>`,
    role: 'Personal trainer',
    imageFileName: 'yanuka-moniaga.jpg',
    specialitities: [],
    imageWidth: '899',
    imageHeight: '1252',
    phone: '0476 63 67 77',
    appointmentHtml:
      '<a href="http://www.yanuka.be/" target="_blank" class="underline" title="http://www.yanuka.be/">http://www.yanuka.be/</a>',
  },
]
